version: "3"

services:

  server:
    build: ./server/
    image: server
    ports: 
      - 5000:5000
      - 80:80
    network_mode: host
 
  client:
    build: ./Interface/
    image: interface
    ports: 
      - 4200:4200
    network_mode: host